# Docker & Azure Container Registry

## Creation

    az acr create -n myregistry -g myResourcegroup --sku Basic --admin-enabled true

## Login

    az acr login -n myregistry

## List ACRs

    az acr list

or for an overview:

    az acr list -o table

## Build locally & push

IMPORTANT: The current folder MUST contain a Dockerfile

    docker build . -t myimage:local
    docker tag myimage:local myregistry.azurecr.io/myimage:v1
    docker push myregistry.azurecr.io/myimage:v1

## Build in ACR

IMPORTANT: You must be logged in

IMPORTANT: The current folder MUST contain a Dockerfile

    az acr build --registry myregistry --image myimage:v1 .

## Get credential

    az acr credential show -n MyRegistry --password-name password2

## Renew credential

    az acr credential renew -n MyRegistry --password-name password2

## Dockerfile

### Install package

#### Alpine

----
RUN apk add --update-cache graphviz \
                           gcc \
                           musl-dev \
    && rm -rf /var/cache/apk/*    
----

#### Ubuntu

----
RUN apt-get update \
    && apt-get install -y \
        graphviz \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
----

#### CentOS

----
RUN yum update -y \
    && yum install -y \
        graphviz \
    && yum clean -y all
----

### Python

----
FROM python:3.8-alpine

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY myscript.py .

CMD [ "python", "./myscript.py" ]
----

### PHP

#### Extension
----
# Install extensions
RUN docker-php-ext-install -j$(nproc) pdo_mysql mbstring zip \
  && docker-php-source delete
----

#### XDEBUG

----
# XDEBUG
# cf. https://github.com/JetBrains/phpstorm-docker-images/blob/master/php-74-apache-xdebug-29/Dockerfile
EXPOSE 9000
RUN pecl install xdebug-2.9.1 \
  &&  docker-php-ext-enable xdebug \
  && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini;
----


#### Composer

----
# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
# Install https://github.com/hirak/prestissimo
 && composer global require hirak/prestissimo

# Copy composer.lock and composer.json
COPY ./composer.lock ./composer.json /var/www/html/
RUN composer install --prefer-dist --no-scripts --no-dev --no-autoloader \
  && rm -rf ~/.composer

# Copy existing application directory contents
COPY . /var/www/html

# Finish composer
RUN composer dump-autoload --no-scripts --no-dev --optimize
----

## Run

### Docker 'run' command to start an interactive bash session 

    docker run -it <image> /bin/bash
    
In case an ENTRYPOINT is defined 

    docker run -it --entrypoint /bin/bash <image>

## Pruning (remove unused objects)

### Images

`-a` will images that are not used by a container

----
docker image prune -a
----

### Containers

`docker ps -a` list all containers, even stopped. By default, only running containers are shown.

----
docker container prune
----

## Logs 

### View logs

----
docker logs <container>
----

### Purge logs

----
echo "" > $(docker inspect --format='{{.LogPath}}' gitlab)
----